; Symbiosis ESP32-S3 AI 陪伴机器人
; 硬件: ESP32-S3-WROOM-N8R8 + MAX98357A + INMP441 + (待)双圆屏

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.psram = enabled

lib_deps =
    bblanchon/ArduinoJson@^7
    lovyan03/LovyanGFX@^1
    earlephilhower/ESP8266Audio@^1
    links2004/WebSockets@^2

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
